### ISSUE TITLE
Internal Server Error for single payment on PayPalService start

### ISSUE THREAD

**Issue by abrgitlab** [paypal/PayPal-Android-SDK#198]
I try to implement single payment. I do all written in https://github.com/paypal/PayPal-Android-SDK/blob/master/docs/single_payment.md

But I've got error "Internal Server Error" when PayPalService starts. Also this error occures when I try to make a payment. It occures at PaymentActivity starting.

09-27 16:39:15.277  21907-21947/travel.line.hotels E/paypal.sdk﹕ request failure with http statusCode:500,exception:org.apache.http.client.HttpResponseException: Internal Server Error
09-27 16:39:15.277  21907-21947/travel.line.hotels E/paypal.sdk﹕ Exception parsing server response
    org.json.JSONException: could not parse:java.lang.NullPointerException	at com.paypal.identity.authnauth.api.policyengine.impl.ScopesPolicyEngine.evaluatePolicies(ScopesPolicyEngine.java:186)	at com.paypal.identity.authnauth.api.policyengi
    nextValue:java.lang.NullPointerException
            at com.paypal.android.sdk.br.n(Unknown Source)
            at com.paypal.android.sdk.cv.d(Unknown Source)
            at com.paypal.android.sdk.bc.a(Unknown Source)
            at com.paypal.android.sdk.bh.a(Unknown Source)
            at com.paypal.android.sdk.bl.a(Unknown Source)
            at com.paypal.android.sdk.aS.a(Unknown Source)
            at com.paypal.android.sdk.aS.b(Unknown Source)
            at com.paypal.android.sdk.aS.b(Unknown Source)
            at com.paypal.android.sdk.aS.a(Unknown Source)
            at com.paypal.android.sdk.aR.a(Unknown Source)
            at com.paypal.android.sdk.aR.run(Unknown Source)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
09-27 16:39:15.277  21907-21947/travel.line.hotels E/paypal.sdk﹕ request failed with server response:java.lang.NullPointerException	at com.paypal.identity.authnauth.api.policyengine.impl.ScopesPolicyEngine.evaluatePolicies(ScopesPolicyEngine.java:186)	at com.paypal.identity.authnauth.api.policyengi
09-27 16:39:15.277  21907-21907/travel.line.hotels E/paypal.sdk﹕ INTERNAL_SERVER_ERROR

**Comment by abrgitlab** [comment]
Oh, I forgot to write, that it happens only if environment is "ENVIRONMENT_PRODUCTION". "ENVIRONMENT_NO_NETWORK" works fine. Sandbox doesn't work for me, but it's another question

**Comment by ppmtscory** [comment]
@abrgitlab can you please make sure that your app that you created on developer.paypal.com has all the required scopes enabled for Production?  It seems like you may be attempting to do something that your account isn't enabled for.  If you can provide the debug_id for the error (should be in the logcat file), I can look that up in our logs as well.

**Comment by ppmtscory** [comment]
Assuming resolution due to inactivity.  If you still experience after enabling all required scopes within your REST App, please open an issue with the debug ID of the error so that it can be researched further.
