### ISSUE TITLE
Upgrading to Paypal Android sdk 2.13.0 crashes the JUnit tests with error java.lang.VerifyError: Expecting a stackmap frame

### ISSUE THREAD

**Issue by aram87** [paypal/PayPal-Android-SDK#245]
I upgraded my android project's PayPal sdk to 2.13.0, accordingly I had to upgrade okhttp and mockwebserver to 2.7.2 due to dependency conflict introduced after upgrading PayPal. Then I pushed the build to a phone and it worked fine. However, when running JUnit tests, they started failing one after the other, on paypal's **CardIOActivity**, displaying a java.lang.VerifyError on each test. The JDK version I use is "1.8.0_66".

**Here is the error message:**

``` sh
java.lang.VerifyError: Expecting a stackmap frame at branch target 12
Exception Details:
  Location:
    io/card/payment/CardIOActivity.<clinit>()V @5: ifne
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 1278 b601 6f9a 0007 04a7 0004 03b3 00a0
    0x0000010: 1204 b300 a9b2 00a9 5904 60b3 00a9 b300
    0x0000020: a1b2 00a9 5904 60b3 00a9 b300 a3b2 00a9
    0x0000030: 5904 60b3 00a9 b300 a4b2 00a9 5904 60b3
    0x0000040: 00a9 b300 a5b2 00a9 5904 60b3 00a9 b300
    0x0000050: a212 78b6 0172 b300 a607 bc0b 5903 0950
    0x0000060: 5904 1400 9750 5905 1400 9350 5906 1400
    0x0000070: 9550 b300 a701 b300 b5b1               

    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at com.paypal.android.sdk.payments.CardIORuntimeAdapter.isCardIOLoaded(Unknown Source)
    at com.paypal.android.sdk.payments.PayPalConfiguration.<init>(Unknown Source)

```

**And here is a snippet of used libraries from build.gradle file:**

``` sh
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.android.support:cardview-v7:22.2.0'
    compile 'com.android.support:recyclerview-v7:22.2.0'
    compile 'com.android.support:design:22.2.0'
    compile 'com.squareup.okhttp:okhttp:2.7.0'
    compile 'org.roboguice:roboguice:3.0.1'
    provided 'org.roboguice:roboblender:3.0.1'
    compile 'uk.co.chrisjenx:calligraphy:2.1.0'
    compile 'com.google.code.gson:gson:2.3.1'
    compile files('lib/HERE-sdk.jar')
    compile 'com.paypal.sdk:paypal-android-sdk:2.13.0'
    compile 'com.google.guava:guava:18.0'
    compile 'com.wdullaer:materialdatetimepicker:1.4.2'
    compile 'com.google.android.gms:play-services-analytics:7.8.0'
    compile 'com.google.android.gms:play-services-gcm:7.8.0'
    compile 'com.pubnub:pubnub-android:3.7.5'
    compile 'org.joda:joda-convert:1.8'
    compile 'org.joda:joda-money:0.10.0'
    compile('commons-validator:commons-validator:1.4.1') {
        transitive = false
    }

    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2'
    androidTestCompile 'com.android.support.test:runner:0.3'
    androidTestCompile 'com.android.support.test:rules:0.3'

    testCompile 'com.squareup.okhttp:mockwebserver:2.7.2'
    testCompile 'junit:junit:4.12'
    testCompile 'org.hamcrest:hamcrest-core:1.1'
    testCompile 'org.hamcrest:hamcrest-library:1.1'
    testCompile 'org.hamcrest:hamcrest-integration:1.1'
    testCompile 'org.robolectric:shadows-support-v4:3.0'
    testCompile 'org.robolectric:robolectric:3.0'
    testCompile 'org.mockito:mockito-core:1.10.19'
```

Can anyone please advise what might be the reason for such crash?

**Comment by lkorth** [comment]
Does this only occur inside of Android Studio or also when running `./gradlew test`?

[android-card-form](https://github.com/braintree/android-card-form) has the same issue when running unit tests from within Android Studio with card.io included. The work around for now is to [set the noverify flag](https://github.com/braintree/android-card-form/blob/44fa7404cee229078cf65bf0ad8da1743aba1d65/CardForm/build.gradle#L17-L23) for unit tests. The fix will be when the next version of card.io is released, since [it targets API 24](https://github.com/card-io/card.io-Android-source/commit/08a5fcefee94a483aef38d077a60a7e5566f85e6) it will have to be compiled with Java 8 and it should no longer produce this verify error. The verify error is a result of card.io being compiled with Java 7 and run with Robolectric on Java 8.

**Comment by OleksandrKucherenko** [comment]
just add `--noverify` into command line of tests runner in Android Studio. Its a problem of Mock libraries actually.

**Comment by pp-randy** [comment]
Is this still ongoing? I see a few card.io releases since Sep 19, 2016 https://github.com/card-io/card.io-Android-source/releases

**Comment by pp-randy** [comment]
Closing due to inactivity
