### ISSUE TITLE
 Unable to start service com.paypal.android.sdk.payments.PayPalService@f782678 with Intent 

### ISSUE THREAD

**Issue by moonandroid** [paypal/PayPal-Android-SDK#290]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal Android SDK Version: 1.14.2
- Android Version and Device (Motorola Droid Razr Maxx with Android 4.4.2, Samsung S7 with Android 6.0, etc...):

### Issue Description
When run the app and getting below error:

java.lang.RuntimeException: Unable to start service com.paypal.android.sdk.payments.PayPalService@f782678 with Intent { cmp=crowdedroad.iFax/com.paypal.android.sdk.payments.PayPalService (has extras) }: java.lang.IllegalStateException: Unable to extract the trust manager on okhttp3.internal.Platform$Android@ee6fbdb, sslSocketFactory is class com.paypal.android.sdk.cg
                                                                      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3027)
                                                                      at android.app.ActivityThread.-wrap17(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                   Caused by: java.lang.IllegalStateException: Unable to extract the trust manager on okhttp3.internal.Platform$Android@ee6fbdb, sslSocketFactory is class com.paypal.android.sdk.cg

We also added OkHttpClient in my app.

**Comment by jaypatel512** [comment]
Have you followed the comments mentioned in the previous issue you opened ? Please make sure to go through them. You need to add the proguard configuration as shown in the comment: https://github.com/paypal/PayPal-Android-SDK/issues/258#issuecomment-188343551

Closing this issue as a duplicate.
