### ISSUE TITLE
Crashes when I allow camera permission.

### ISSUE THREAD

**Issue by nallwhy** [paypal/PayPal-Android-SDK#291]
### Required Information

- Mode (Mock/Sandbox/Live): Live
- PayPal Android SDK Version: 2.14.2
- Android Version and Device (Motorola Droid Razr Maxx with Android 4.4.2, Samsung S7 with Android 6.0, etc...): Samsung S5 with Android 6.0
- PayPal-Debug-ID(s) (from any logs):

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.

I **disalbed** card.io card scanning.
But Paypal asks me "Allow App to take pictures and record video?" when I choose "Pay with Card", and if I **allow** it, the app crashes at the first time.
The following is error log.

05-23 14:23:38.733 794-794/kr.co.cultrip.www.cultrip E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: kr.co.cultrip.www.cultrip, PID: 794
                                                                       java.lang.UnsatisfiedLinkError: No implementation found for void io.card.payment.CardScanner.nSetup(boolean, float) (tried Java_io_card_payment_CardScanner_nSetup and Java_io_card_payment_CardScanner_nSetup__ZF)
                                                                           at io.card.payment.CardScanner.nSetup(Native 0Method)
                                                                           at io.card.payment.CardScanner.<init>(CardScanner.java:168)
                                                                           at io.card.payment.CardIOActivity.showCameraScannerOverlay(CardIOActivity.java:477)
                                                                           at io.card.payment.CardIOActivity.onRequestPermissionsResult(CardIOActivity.java:643)
                                                                           at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7263)
                                                                           at android.app.Activity.dispatchActivityResult(Activity.java:7141)
                                                                           at android.app.ActivityThread.deliverResults(ActivityThread.java:4916)
                                                                           at android.app.ActivityThread.handleSendResult(ActivityThread.java:4963)
                                                                           at android.app.ActivityThread.access$1600(ActivityThread.java:221)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1848)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:158)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by jaypatel512** [comment]
Have you followed these steps to disable card scanning ? https://github.com/paypal/PayPal-Android-SDK#disabling-cardio-card-scanning

**Comment by nallwhy** [comment]
@jaypatel512 Yes. I don't know why paypal sdk asks the camera permission even though I've disabled it.

**Comment by jaypatel512** [comment]
Is the device you tested a physical, or an emulator. I am hoping to reproduce it on my side to figure out why it is doing that.

**Comment by nallwhy** [comment]
Physical Samsung S5 with Android 6.0.
Is it not reproducible?

**Comment by jaypatel512** [comment]
Are you sure you have kept `packagingOptions` inside the `andorid` block in build.gradle. I am not able to reproduce this issue on device or simulator. 

Here is how the build.gradle in [sample](https://github.com/paypal/PayPal-Android-SDK/blob/master/SampleApp/build.gradle) would look like with card.io scanning disabled. Notice the `packagingOptions` inside `android`.

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
    }
}

repositories {
    maven {
        // Used for downloading dependency com.github.lkorth:device-automator
        url "https://jitpack.io"
    }
    mavenCentral()
}

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.1'

    defaultConfig {
        minSdkVersion 18
        targetSdkVersion 23
        testInstrumentationRunner 'android.support.test.runner.AndroidJUnitRunner'
    }

    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    // Only for SampleApp.
    // It is failing because the okio version and okhttp is not found, which is expected.
    lintOptions {
        abortOnError false
    }


    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            signingConfig signingConfigs.debug
        }

        release{
            minifyEnabled true
            proguardFile getDefaultProguardFile('proguard-android.txt')
            signingConfig signingConfigs.release
        }
    }

    android.applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def outputFile = output.outputFile
            if (outputFile != null && outputFile.name.endsWith('.apk')) {
                output.outputFile = new File(outputFile.parent, "paypal-sample-app-${variant.name}.apk")
            }
        }
    }

    productFlavors {
        general
        partner
    }


    // this is what disables card.io scanning. Please make sure this exists in your code.
    packagingOptions {
        exclude 'lib/arm64-v8a/libcardioDecider.so'
        exclude 'lib/arm64-v8a/libcardioRecognizer.so'
        exclude 'lib/arm64-v8a/libcardioRecognizer_tegra2.so'
        exclude 'lib/arm64-v8a/libopencv_core.so'
        exclude 'lib/arm64-v8a/libopencv_imgproc.so'
        exclude 'lib/armeabi/libcardioDecider.so'
        exclude 'lib/armeabi-v7a/libcardioDecider.so'
        exclude 'lib/armeabi-v7a/libcardioRecognizer.so'
        exclude 'lib/armeabi-v7a/libcardioRecognizer_tegra2.so'
        exclude 'lib/armeabi-v7a/libopencv_core.so'
        exclude 'lib/armeabi-v7a/libopencv_imgproc.so'
        exclude 'lib/mips/libcardioDecider.so'
        exclude 'lib/x86/libcardioDecider.so'
        exclude 'lib/x86/libcardioRecognizer.so'
        exclude 'lib/x86/libcardioRecognizer_tegra2.so'
        exclude 'lib/x86/libopencv_core.so'
        exclude 'lib/x86/libopencv_imgproc.so'
        exclude 'lib/x86_64/libcardioDecider.so'
        exclude 'lib/x86_64/libcardioRecognizer.so'
        exclude 'lib/x86_64/libcardioRecognizer_tegra2.so'
        exclude 'lib/x86_64/libopencv_core.so'
        exclude 'lib/x86_64/libopencv_imgproc.so'
    }
}

configurations.all {
    resolutionStrategy.force 'com.android.support:support-annotations:23.0.1'
}


dependencies {
    compile('com.paypal.sdk:paypal-android-sdk:2.14.2')
    compile 'com.google.android.gms:play-services-wallet:8.4.0'

    testCompile 'com.android.support.test.espresso:espresso-core:2.2.1'
    androidTestCompile 'com.github.lkorth:device-automator:30238040d8'
    testCompile 'com.google.dexmaker:dexmaker-mockito:1.1'
    testCompile 'com.android.support.test.espresso:espresso-intents:2.2.1'
    testCompile 'com.android.support.test.espresso:espresso-web:2.2.1'
    testCompile 'com.android.support.test:runner:0.4.1'
    testCompile 'com.android.support.test:rules:0.4.1'
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.12'
}
```

**Comment by nallwhy** [comment]
I can't reproduce it now.. even though I didn't change any code about paypal.
I'm sorry for confusing you.
