### ISSUE TITLE
Unable to start activity 

### ISSUE THREAD

**Issue by auxDK** [paypal/PayPal-Android-SDK#366]
### Required Information

- Mode (Mock/Sandbox/Live): Live
- PayPal Android SDK Version: 2.15
- Android Version and Device : BATMOBILE XT320 4.3.1
- Android buildToolsVersion : 24.0.3

### Issue Description
>Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.autodoc.gmbh/com.paypal.android.sdk.payments.LoginActivity}: java.lang.NullPointerException

**Comment by jaypatel512** [comment]
Hey @auxDK !

We tried reproducing the issue in live/sandbox, and were not able to do so. Such a null pointer exception could happen if your device was getting out of memory, or running into a corner case scenario. Can you please reproduce the issue with a different device/emulator, and see if you are consistently seeing this error ?

If so, can you please re-open this issue with steps to reproduce and null pointer exception trace please, so that we can figure out where exactly this is happening ? Thanks.

**Comment by hmedat2008** [comment]
@jaypatel512  
Check this stack-trace

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.opensooq.OpenSooq/com.paypal.android.sdk.payments.LoginActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2118)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2145)
       at android.app.ActivityThread.access$600(ActivityThread.java:130)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at com.paypal.android.sdk.payments.LoginActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:5187)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2145)
       at android.app.ActivityThread.access$600(ActivityThread.java:130)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by pp-randy** [comment]
@hmedat2008 can you file a new issue with your most recent error.  I'm not sure if you were able to resolve with my recent comment on https://github.com/paypal/PayPal-Android-SDK/issues/81.
