### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by rodrigobertet** [paypal/PayPal-Android-SDK#372]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox (in Mock it works)
- PayPal Android SDK Version: compile('com.paypal.sdk:paypal-android-sdk:2.15.1') {
        exclude group: 'io.card'
    }
- Android Version and Device Xiaomi Redmi Note 2 Android 5.0.2:
- PayPal-Debug-ID(s) (from any logs): 

### Issue Description
I am developing with Android Studio in native. When I try to start Service the app crashes and Log gives me this error:

java.lang.RuntimeException: Unable to start service com.paypal.android.sdk.payments.PayPalService@38b6e1f7 with Intent { cmp=com.apelucy.apelucy/com.paypal.android.sdk.payments.PayPalService (has extras) }: java.lang.RuntimeException: Service extras invalid.  Please check the docs.
                                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3063)
                                                                       at android.app.ActivityThread.access$2100(ActivityThread.java:169)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1521)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                       at android.os.Looper.loop(Looper.java:194)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                                                                    Caused by: java.lang.RuntimeException: Service extras invalid.  Please check the docs.
                                                                       at com.paypal.android.sdk.payments.PayPalService.a(Unknown Source)
                                                                       at com.paypal.android.sdk.payments.PayPalService.onStartCommand(Unknown Source)
                                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3046)
                                                                       at android.app.ActivityThread.access$2100(ActivityThread.java:169) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1521) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                       at android.os.Looper.loop(Looper.java:194) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5546) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 

This is my code:

    public static PayPalConfiguration paypalConfig;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        paypalConfig= new PayPalConfiguration()
                .environment(PayPalConfiguration.ENVIRONMENT_SANDBOX)
                .clientId(MyApplication.getAppContext().getString(R.string.paypal_client_id))
                .acceptCreditCards(false)
                .rememberUser(true);

        Bundle b = getIntent().getExtras();
        precioTotal = b.getFloat(PRECIO_TOTAL);
        orderId = b.getInt(ORDER_ID);

        Intent intent = new Intent(this, PayPalService.class);
        intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, paypalConfig);
        startService(intent);
    }

**Comment by rodrigobertet** [comment]
I am in debug mode and working with okhttp 2.7.5

**Comment by harshtanwar29** [comment]
10-23 16:27:53.112 2765-2765/com.imate.android E/Abhimanyu: Location updateLocation:::null
10-23 16:28:00.977 2765-2765/com.imate.android E/PayPalConfiguration: clientId contains whitespace.
    clientId is invalid.  Please see the docs.
10-23 16:28:00.978 2765-2765/com.imate.android E/UncaughtException: java.lang.RuntimeException: Unable to bind to service com.paypal.android.sdk.payments.PayPalService@19b4a2f with Intent { cmp=com.imate.android/com.paypal.android.sdk.payments.PayPalService (has extras) }: java.lang.RuntimeException: Service extras invalid.  Please check the docs.
        at android.app.ActivityThread.handleBindService(ActivityThread.java:3224)
        at android.app.ActivityThread.-wrap3(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1568)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
     Caused by: java.lang.RuntimeException: Service extras invalid.  Please check the docs.
        at com.paypal.android.sdk.payments.PayPalService.a(Unknown Source)
        at com.paypal.android.sdk.payments.PayPalService.onBind(Unknown Source)
        at android.app.ActivityThread.handleBindService(ActivityThread.java:3210)
        at android.app.ActivityThread.-wrap3(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1568) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6123) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
10-23 16:28:01.204 2765-2765/com.imate.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.imate.android, PID: 2765
    java.lang.RuntimeException: Unable to bind to service com.paypal.android.sdk.payments.PayPalService@19b4a2f with Intent { cmp=com.imate.android/com.paypal.android.sdk.payments.PayPalService (has extras) }: java.lang.RuntimeException: Service extras invalid.  Please check the docs.
        at android.app.ActivityThread.handleBindService(ActivityThread.java:3224)
        at android.app.ActivityThread.-wrap3(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1568)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
     Caused by: java.lang.RuntimeException: Service extras invalid.  Please check the docs.
        at com.paypal.android.sdk.payments.PayPalService.a(Unknown Source)
        at com.paypal.android.sdk.payments.PayPalService.onBind(Unknown Source)
        at android.app.ActivityThread.handleBindService(ActivityThread.java:3210)
        at android.app.ActivityThread.-wrap3(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1568) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6123) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by Santosh-Chauhan** [comment]
What was the solution? Not mentioned above.
