### ISSUE TITLE
System Error. Please try again later.

### ISSUE THREAD

**Issue by sundeepkmallick** [paypal/PayPal-Android-SDK#388]
### General information

* SDK/Library version: 2.14.6
* Environment: Sandbox
* `PayPal-Debug-ID` values: 24e13aee54aba
* Android Version and Device: Nexus 6, Android OS 7.0

### Issue description

After I login using paypal's sandbox credential, when I am pressing the "Agree" button, I am getting a pop-up showing "System Error. Please try again later.".  This issue was not happening earlier. But now it's happening for all the Paypal SDK version. Below is the error log. Please help to solve this issue.

### Error Log

03-08 14:07:10.939 2937-8677/ W/paypal.sdk: fe SN:11 PayPal Debug-ID: 24e13aee54aba [sandbox, 2.14.6;release]
03-08 14:07:10.939 2937-8677/ E/paypal.sdk: request failure with http statusCode:401,exception:Unauthorized
03-08 14:07:10.942 2937-8677/ E/paypal.sdk: Exception parsing server response
                                                                org.json.JSONException: End of input at character 0 of 
                                                                    at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
                                                                    at org.json.JSONTokener.nextValue(JSONTokener.java:97)
                                                                    at com.paypal.android.sdk.cv.m(Unknown Source)
                                                                    at com.paypal.android.sdk.fe.d(Unknown Source)
                                                                    at com.paypal.android.sdk.ch.a(Unknown Source)
                                                                    at com.paypal.android.sdk.cl.a(Unknown Source)
                                                                    at com.paypal.android.sdk.cp.onResponse(Unknown Source)
                                                                    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
                                                                    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                    at java.lang.Thread.run(Thread.java:761)
03-08 14:07:10.944 2937-8677/ E/paypal.sdk: request failed with server response:
03-08 14:07:10.945 2937-2937/E/paypal.sdk: INTERNAL_SERVER_ERROR

**Comment by sundeepkmallick** [comment]
Don't know it started working again!! Probably the issue was from Paypal server end..

**Comment by haseelrefl** [comment]
Facing the issue today.

**Comment by xiaoleih41** [comment]
Can you tell me what exact API call are you trying make? What are you trying to achieve in the call? It will help me troubleshoot.

**Comment by haseelrefl** [comment]
I am using the Paypal iOS SDK in sandbox mode. Login to paypal account
works fine. Next I click PAY and this message is displayed as an alert. The
same happens with Paypal Android SDK too.

**Comment by xiaoleih41** [comment]
These two SDKs are deprecated. Please find more detail [here](https://developer.paypal.com/docs/integration/mobile/mobile-sdk-overview/#paypal-mobile-sdks) and follow the guide for the alternative products.
