### ISSUE TITLE
Crash - PaymentActivity - requestFeature

### ISSUE THREAD

**Issue by prcaen** [paypal/PayPal-Android-SDK#396]
### General information

* SDK/Library version: 2.13.3 and 2.15.3 (tested on both)
* Environment: Production
* PayPal-Debug-ID values: c02ea1be1e2ed
* Android Version and Device: Android 6.0 API 23; unknown Android SDK built for x86_64; also
* Android Target version: 25
* Min SDK version: 16
* Android Build tool version: 25.0.2
* Android gradle plugin: 2.3.0
* Support lib version: 25.2.0
* Play Services version: 10.0.1
* Gradle version: 3.4

### Issue description
When we send the user to `PaymentActivity` through the following Intent:
```java
PayPalConfiguration config = // ...
Intent serviceIntent = new Intent(this, PayPalService.class);
serviceIntent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, config);
startService(serviceIntent);
Intent intent = new Intent(this, PaymentActivity.class);
intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, config);
intent.putExtra(PaymentActivity.EXTRA_PAYMENT, payment);
startActivityForResult(intent, 0);
```

The following crash appears:
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.package.app/com.paypal.android.sdk.payments.PaymentActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
    at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:317)
    at android.app.Activity.requestWindowFeature(Activity.java:3650)
    at com.paypal.android.sdk.d.a(Unknown Source)
    at com.paypal.android.sdk.payments.PaymentActivity.onCreate(Unknown Source)
    at android.app.Activity.performCreate(Activity.java:6237)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5417) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

After looking at the StackTrace, you are requesting the Toolbar after setContentView.
Also apparently there is no theme use by the `PaymentActivity`.

In order to try to resolve the issue, we started to provide a Theme, the `Theme.Material` (available since 5.0 - API 21) which solve the issue only on API level 24 and 25 but still present on API  level from 16 to 23.

Any idea? Any way to fix it on your side?
Thanks.

**Comment by pp-randy** [comment]
When researching this issue I came across http://stackoverflow.com/questions/16939814/android-util-androidruntimeexception-requestfeature-must-be-called-before-add

**Comment by prcaen** [comment]
Hello,

we finally found the issue. We were getting the Window before the setContent was done thanks to [ActivityLifecycleCallback of the Application](https://developer.android.com/reference/android/app/Application.ActivityLifecycleCallbacks.html).

Thanks.

**Comment by EddyAnd** [comment]
can you  tell me  how  to  solve this issue?

**Comment by EddyAnd** [comment]
how to solve?Thanks @prcaen

**Comment by pp-randy** [comment]
@EddyAnd it think it came down to when various methods were called.

In the example app the PayPalService is started in OnCreate
https://github.com/paypal/PayPal-Android-SDK/blob/master/SampleApp/src/main/java/com/paypal/example/paypalandroidsdkexample/SampleActivity.java#L72-L79

**Comment by pp-randy** [comment]
If you provide some examples @EddyAnd of when in the lifecycle you are calling the PayPal functions I can escalate for some further assistance if you and I can't figure it out.

**Comment by EddyAnd** [comment]
@pp-randy  The probability of the original problem is very low, and now I am revised by your suggestion, so far, has not yet appeared, I do not know if there is a real solution to this problem. Thank you, are there any other things to note?

**Comment by xiaoleih41** [comment]
There's no other things to note at this time. Please resubmit when you encounter this issue again with `debugId` for us to do further research.

**Comment by EddyAnd** [comment]
@xiaoleih41  java.lang.RuntimeException: Unable to start activity ComponentInfo{leedarson.platformapp/com.paypal.android.sdk.payments.PaymentActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setBackgroundDrawable(android.graphics.drawable.Drawable)' on a null object reference
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                        at android.os.Looper.loop(Looper.java:156)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6531)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
                                                                     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setBackgroundDrawable(android.graphics.drawable.Drawable)' on a null object reference
                                                                        at com.paypal.android.sdk.d.a(Unknown Source)
                                                                        at com.paypal.android.sdk.payments.d.a(Unknown Source)
                                                                        at com.paypal.android.sdk.payments.PaymentActivity.onCreate(Unknown Source)
                                                                        at android.app.Activity.performCreate(Activity.java:6910)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                        at android.os.Looper.loop(Looper.java:156) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6531) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by EddyAnd** [comment]
The previous question did not happen again, but there was a new problem.

**Comment by jaypatel512** [comment]
Hey @EddyAnd ! Can you please tell us the PayPal SDK version you are using ? We need to know that to do a proper stack trace.
