### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method sslSocketFactory

### ISSUE THREAD

**Issue by sudheeshde** [paypal/PayPal-Android-SDK#408]
### General information

* SDK/Library version: paypal-android-sdk:2.15.3
* Environment:  Sandbox 
* Android Version and Device: Xiaomi Redmi 3S with Android 6.0 

### Issue description
This service was working fine till yesterday, before I'm integrated Paytabs aar module into my application. Now I'm getting this exception 
`java.lang.NoSuchMethodError: No virtual method sslSocketFactory(Ljavax/net/ssl/SSLSocketFactory;Ljavax/net/ssl/X509TrustManager;)Lokhttp3/OkHttpClient$Builder; in class Lokhttp3/OkHttpClient$Builder; or its super classes (declaration of 'okhttp3.OkHttpClient$Builder' appears in /data/app/com.package-2/split_lib_dependencies_apk.apk:classes43.dex)
                                                                       at com.paypal.android.sdk.ca.a(Unknown Source)
                                                                       at com.paypal.android.sdk.ca.a(Unknown Source)
                                                                       at com.paypal.android.sdk.ca.a(Unknown Source)
                                                                       at com.paypal.android.sdk.ci.<init>(Unknown Source)
                                                                       at com.paypal.android.sdk.payments.PayPalService.a(Unknown Source)
                                                                       at com.paypal.android.sdk.payments.PayPalService.onStartCommand(Unknown Source)
                                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3017)
                                                                       at android.app.ActivityThread.access$2200(ActivityThread.java:153)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)`

this is my gradle where retrofit and okhttp are specified 
` compile 'com.squareup.okhttp:okhttp:2.7.5'
  compile 'com.squareup.retrofit2:retrofit:2.2.0'
  compile 'com.squareup.retrofit2:converter-gson:2.2.0'
  compile 'com.squareup.okhttp3:logging-interceptor:3.3.1'
  compile 'com.paypal.sdk:paypal-android-sdk:2.15.3'`
Paypal sdk  is working without the Paytabs aar module. 
I'm not sure that this happened due to Paytabs aar module. Please suggest a way to handle this error.

**Edit :**  This is my proguard 
`-dontwarn okio.**
-dontwarn javax.annotation.Nullable
-dontwarn javax.annotation.ParametersAreNonnullByDefault
-dontwarn org.apache.http.**
-keep class org.apache.http.* { *; }
-dontwarn sun.misc.Unsafe
-dontwarn retrofit2.**
-dontwarn javax.annotation.**
-keep class retrofit2.** { *; }
-keepattributes Signature
-keepattributes Exceptions

-keepclasseswithmembers class * {
    @retrofit2.http.* <methods>;
}
-keepclassmembers class * implements javax.net.ssl.SSLSocketFactory {
    private javax.net.ssl.SSLSocketFactory delegate;
}`

**Comment by jaypatel512** [comment]
Hey @sudheeshde !

Let me try and reproduce this issue. In the mean time, can you please try and see if updating okhttp to latest version solves this issue or not ? 

retrofit might also download okhttp as a dependency. Double check which version exactly is getting downloaded.

**Comment by jaypatel512** [comment]
On further review, it looks like your app will download both `okhttp:2.7.5`, and `okhttp:3.6.0`. You need to make sure you only use one version of okhttp in your system. Try removing `okhttp:2.7.5` as a dependency, and let me know if that solves the issue.

**Comment by sudheeshde** [comment]
Hi @jaypatel512 , 
After removing `okhttp:2.7.5`, it works fine. 
Thank you for the help. And also I'm updated to `okhttp:3.6.0`.  Cheers..!
