### ISSUE TITLE
NullPointerException in PaymentConfirmationActivity

### ISSUE THREAD

**Issue by mohammad-haque** [paypal/PayPal-Android-SDK#439]
### General information
* SDK/Library version: 2.15.3
* Environment: Prod
* Android Version and Device: version 4, devices: appearing 'unknown' in Crashlytics

### Issue description
Seeing this NPE for few people. Reason is not very clear as it is happening inside the activity that is part of the SDK. Here is the log:

Caused by java.lang.NullPointerException
       at com.paypal.android.sdk.payments.PaymentConfirmActivity.onBackPressed(Unknown Source)
       at com.paypal.android.sdk.payments.PaymentConfirmActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:5187)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2145)
       at android.app.ActivityThread.access$600(ActivityThread.java:130)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by xiaoleih41** [comment]
This SDK is now deprecated. Please consider to integrate Braintree direct or Express Checkout with Braintree SDK. For more detail, please check [here](https://developer.paypal.com/docs/integration/mobile/mobile-sdk-overview/#paypal-mobile-sdks)
