### ISSUE TITLE
Invalid Path?

### ISSUE THREAD

**Issue by Ryuinferno** [paypal/PayPal-Android-SDK#77]
We have been integrating the SDK into our project, it works fine in most devices expect for this one (LG Optimus 4X HD).

This is the stack trace:

```
06-27 23:32:10.606 18561 18561 E PayPalService: Risk component failed to initialize, threw Invalid path: /storage/emulated/0
06-27 23:32:10.906 18561 18985 W dalvikvm: threadid=21: thread exiting with uncaught exception (group=0x4184cce0)
06-27 23:32:10.916 18561 18985 E AndroidRuntime: FATAL EXCEPTION: Thread-2264
06-27 23:32:10.916 18561 18985 E AndroidRuntime: Process: com.android.settings, PID: 18561
06-27 23:32:10.916 18561 18985 E AndroidRuntime: java.lang.IllegalArgumentException: Invalid path: /storage/emulated/0
06-27 23:32:10.916 18561 18985 E AndroidRuntime:    at android.os.StatFs.doStat(StatFs.java:46)
06-27 23:32:10.916 18561 18985 E AndroidRuntime:    at android.os.StatFs.<init>(StatFs.java:39)
06-27 23:32:10.916 18561 18985 E AndroidRuntime:    at com.paypal.android.sdk.bj.c(Unknown Source)
06-27 23:32:10.916 18561 18985 E AndroidRuntime:    at com.paypal.android.sdk.aW.g(Unknown Source)
06-27 23:32:10.916 18561 18985 E AndroidRuntime:    at com.paypal.android.sdk.aW.b(Unknown Source)
06-27 23:32:10.916 18561 18985 E AndroidRuntime:    at com.paypal.android.sdk.aa.a(Unknown Source)
06-27 23:32:10.916 18561 18985 E AndroidRuntime:    at com.paypal.android.sdk.H.run(Unknown Source)
06-27 23:32:10.916 18561 18985 E AndroidRuntime: Caused by: libcore.io.ErrnoException: statvfs failed: EACCES (Permission denied)
06-27 23:32:10.916 18561 18985 E AndroidRuntime:    at libcore.io.Posix.statvfs(Native Method)
06-27 23:32:10.916 18561 18985 E AndroidRuntime:    at libcore.io.ForwardingOs.statvfs(ForwardingOs.java:132)
06-27 23:32:10.916 18561 18985 E AndroidRuntime:    at android.os.StatFs.doStat(StatFs.java:44)
06-27 23:32:10.916 18561 18985 E AndroidRuntime:    ... 6 more
```

Thank you

**Comment by Pavel87** [comment]
What was the issue at the end?

**Comment by NinoDLC** [comment]
BUMP

**Comment by pp-randy** [comment]
I apologize I am unfamiliar with the cause of this issue; however, I assume if you are seeing an invalid path error now with an updated release the cause would be different since this issue is from 2014.  If you are seeing issues for Invalid Path with the most recent release could you create a new issue?
