### ISSUE TITLE
Service Binding Error

### ISSUE THREAD

**Issue by tarekf** [paypal/PayPal-Android-SDK#81]
After moving from the 1.0 SDK to the 2.0 SDK, we are seeing an error firing with our users related to service binding. The stack trace we are seeing is:

```
java.lang.RuntimeException: Unable to bind to service com.paypal.android.sdk.payments.PayPalService@4230c478 with Intent { cmp=com.contextlogic.wish/com.paypal.android.sdk.payments.PayPalService (has extras) }: java.lang.RuntimeException: Service extras required. Please see the docs.
   at android.app.ActivityThread.handleBindService(ActivityThread.java:2624)
   at android.app.ActivityThread.access$1900(ActivityThread.java:139)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:136)
   at android.app.ActivityThread.main(ActivityThread.java:5086)
   at java.lang.reflect.Method.invokeNative(Method.java)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
   at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.RuntimeException: Service extras required. Please see the docs.
   at com.paypal.android.sdk.payments.PayPalService.a()
   at com.paypal.android.sdk.payments.PayPalService.onBind()
   at android.app.ActivityThread.handleBindService(ActivityThread.java:2611)
   at android.app.ActivityThread.access$1900(ActivityThread.java:139)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:136)
   at android.app.ActivityThread.main(ActivityThread.java:5086)
   at java.lang.reflect.Method.invokeNative(Method.java)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
   at dalvik.system.NativeStart.main(NativeStart.java)
```

We are starting the service in onCreate and always pass extras as required, and we are stopping the service in onDestroy as described in the doc.

We can't reproduce the issue ourselves, and don't have visibility to the underlying code to understand the issue further.

**Comment by hmedat2008** [comment]
Still I'm facing the issue:
`Fatal Exception: java.lang.RuntimeException: Unable to start service com.paypal.android.sdk.payments.PayPalService@415f9608 with Intent { cmp=x.x.x/com.paypal.android.sdk.payments.PayPalService }: java.lang.RuntimeException: Service extras required. Please see the docs.
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2608)
       at android.app.ActivityThread.access$1900(ActivityThread.java:130)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.RuntimeException: Service extras required. Please see the docs.
       at com.paypal.android.sdk.payments.PayPalService.onStartCommand(Unknown Source)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2591)
       at android.app.ActivityThread.access$1900(ActivityThread.java:130)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
`

**Comment by pp-randy** [comment]
You need `intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, config);`
